/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AuthAuthImport } from './routes/auth/_auth'
import { Route as AppAuthenticatedImport } from './routes/_app/_authenticated'
import { Route as AuthAuthRegisterImport } from './routes/auth/_auth.register'
import { Route as AuthAuthLogoutImport } from './routes/auth/_auth.logout'
import { Route as AuthAuthLoginImport } from './routes/auth/_auth.login'
import { Route as AppAuthenticatedDashboardIndexImport } from './routes/_app/_authenticated/dashboard/index'
import { Route as AppAuthenticatedUserVehiclesIndexImport } from './routes/_app/_authenticated/user/vehicles/index'
import { Route as AppAuthenticatedUserJourneysIndexImport } from './routes/_app/_authenticated/user/journeys/index'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/_auth',
  getParentRoute: () => AuthRoute,
} as any)

const AppAuthenticatedRoute = AppAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRoute,
} as any)

const AuthAuthRegisterRoute = AuthAuthRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthLogoutRoute = AuthAuthLogoutImport.update({
  path: '/logout',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthLoginRoute = AuthAuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AppAuthenticatedDashboardIndexRoute =
  AppAuthenticatedDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)

const AppAuthenticatedUserVehiclesIndexRoute =
  AppAuthenticatedUserVehiclesIndexImport.update({
    path: '/user/vehicles/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)

const AppAuthenticatedUserJourneysIndexRoute =
  AppAuthenticatedUserJourneysIndexImport.update({
    path: '/user/journeys/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/_authenticated': {
      id: '/_app/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthenticatedImport
      parentRoute: typeof AppImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_auth': {
      id: '/auth/_auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_auth/login': {
      id: '/auth/_auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/logout': {
      id: '/auth/_auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthAuthLogoutImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/register': {
      id: '/auth/_auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthRegisterImport
      parentRoute: typeof AuthAuthImport
    }
    '/_app/_authenticated/dashboard/': {
      id: '/_app/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthenticatedDashboardIndexImport
      parentRoute: typeof AppAuthenticatedImport
    }
    '/_app/_authenticated/user/journeys/': {
      id: '/_app/_authenticated/user/journeys/'
      path: '/user/journeys'
      fullPath: '/user/journeys'
      preLoaderRoute: typeof AppAuthenticatedUserJourneysIndexImport
      parentRoute: typeof AppAuthenticatedImport
    }
    '/_app/_authenticated/user/vehicles/': {
      id: '/_app/_authenticated/user/vehicles/'
      path: '/user/vehicles'
      fullPath: '/user/vehicles'
      preLoaderRoute: typeof AppAuthenticatedUserVehiclesIndexImport
      parentRoute: typeof AppAuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedDashboardIndexRoute: typeof AppAuthenticatedDashboardIndexRoute
  AppAuthenticatedUserJourneysIndexRoute: typeof AppAuthenticatedUserJourneysIndexRoute
  AppAuthenticatedUserVehiclesIndexRoute: typeof AppAuthenticatedUserVehiclesIndexRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedDashboardIndexRoute: AppAuthenticatedDashboardIndexRoute,
  AppAuthenticatedUserJourneysIndexRoute:
    AppAuthenticatedUserJourneysIndexRoute,
  AppAuthenticatedUserVehiclesIndexRoute:
    AppAuthenticatedUserVehiclesIndexRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

interface AppRouteChildren {
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthAuthRouteChildren {
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthLogoutRoute: typeof AuthAuthLogoutRoute
  AuthAuthRegisterRoute: typeof AuthAuthRegisterRoute
}

const AuthAuthRouteChildren: AuthAuthRouteChildren = {
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthLogoutRoute: AuthAuthLogoutRoute,
  AuthAuthRegisterRoute: AuthAuthRegisterRoute,
}

const AuthAuthRouteWithChildren = AuthAuthRoute._addFileChildren(
  AuthAuthRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthRoute: typeof AuthAuthRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthRoute: AuthAuthRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppAuthenticatedRouteWithChildren
  '/auth': typeof AuthAuthRouteWithChildren
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/logout': typeof AuthAuthLogoutRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/dashboard': typeof AppAuthenticatedDashboardIndexRoute
  '/user/journeys': typeof AppAuthenticatedUserJourneysIndexRoute
  '/user/vehicles': typeof AppAuthenticatedUserVehiclesIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AppAuthenticatedRouteWithChildren
  '/auth': typeof AuthAuthRouteWithChildren
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/logout': typeof AuthAuthLogoutRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/dashboard': typeof AppAuthenticatedDashboardIndexRoute
  '/user/journeys': typeof AppAuthenticatedUserJourneysIndexRoute
  '/user/vehicles': typeof AppAuthenticatedUserVehiclesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_auth': typeof AuthAuthRouteWithChildren
  '/auth/_auth/login': typeof AuthAuthLoginRoute
  '/auth/_auth/logout': typeof AuthAuthLogoutRoute
  '/auth/_auth/register': typeof AuthAuthRegisterRoute
  '/_app/_authenticated/dashboard/': typeof AppAuthenticatedDashboardIndexRoute
  '/_app/_authenticated/user/journeys/': typeof AppAuthenticatedUserJourneysIndexRoute
  '/_app/_authenticated/user/vehicles/': typeof AppAuthenticatedUserVehiclesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/dashboard'
    | '/user/journeys'
    | '/user/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/auth'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/dashboard'
    | '/user/journeys'
    | '/user/vehicles'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_authenticated'
    | '/auth'
    | '/auth/_auth'
    | '/auth/_auth/login'
    | '/auth/_auth/logout'
    | '/auth/_auth/register'
    | '/_app/_authenticated/dashboard/'
    | '/_app/_authenticated/user/journeys/'
    | '/_app/_authenticated/user/vehicles/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/auth"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_authenticated"
      ]
    },
    "/_app/_authenticated": {
      "filePath": "_app/_authenticated.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_authenticated/dashboard/",
        "/_app/_authenticated/user/journeys/",
        "/_app/_authenticated/user/vehicles/"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_auth"
      ]
    },
    "/auth/_auth": {
      "filePath": "auth/_auth.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_auth/login",
        "/auth/_auth/logout",
        "/auth/_auth/register"
      ]
    },
    "/auth/_auth/login": {
      "filePath": "auth/_auth.login.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/logout": {
      "filePath": "auth/_auth.logout.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/register": {
      "filePath": "auth/_auth.register.tsx",
      "parent": "/auth/_auth"
    },
    "/_app/_authenticated/dashboard/": {
      "filePath": "_app/_authenticated/dashboard/index.tsx",
      "parent": "/_app/_authenticated"
    },
    "/_app/_authenticated/user/journeys/": {
      "filePath": "_app/_authenticated/user/journeys/index.tsx",
      "parent": "/_app/_authenticated"
    },
    "/_app/_authenticated/user/vehicles/": {
      "filePath": "_app/_authenticated/user/vehicles/index.tsx",
      "parent": "/_app/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
